# Generated by Django 3.2.7 on 2021-10-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(help_text='Year-Month-Day', null=True),
        ),
    ]
