# Generated by Django 3.2.7 on 2021-09-27 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20210927_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Year/Month/Day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='random_number',
            field=models.PositiveIntegerField(default=47),
        ),
    ]
