# Generated by Django 3.2.7 on 2021-09-27 21:50

import MyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_user_random_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_number',
            field=models.PositiveIntegerField(default=MyApp.models.get_rnd, editable=False),
        ),
    ]
